# Generated by Django 4.0.3 on 2022-04-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=70)),
                ('desig', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField(default=18)),
                ('salary', models.PositiveIntegerField(default=5000)),
            ],
        ),
    ]
